type token =
  | EOF
  | IDENTIFIER of (string)
  | KEYWORD_ANALYZE
  | KEYWORD_CELL
  | KEYWORD_COMPUTAD
  | KEYWORD_FUN
  | KEYWORD_NORMALIZE
  | KEYWORD_SIGN
  | KEYWORD_STAR
  | LEFT_PARENTHESIS
  | LEFT_SQUARE_BRACKET
  | RIGHT_PARENTHESIS
  | RIGHT_SQUARE_BRACKET
  [@@deriving eq, ord, show]
