type token =
  | EOF
  | IDENTIFIER string
  | KEYWORD_ANALYZE
  | KEYWORD_ARITY
  | KEYWORD_CELL
  | KEYWORD_COMPUTAD
  | KEYWORD_LAMBDA
  | KEYWORD_SIGN
  | KEYWORD_TYPE
  | LEFT_PARENTHESIS
  | LEFT_SQUARE_BRACKET
  | RIGHT_PARENTHESIS
  | RIGHT_SQUARE_BRACKET
  [@@deriving (eq, ord, show)];
